import time
import os
from Piano import tocar_som
from Piano import notas

@-----------------------------------------------------------------------------@
def parabens():
  tocar_som(os.path.join(notas, "g1.wav"))
  time.sleep(0.53)
  tocar_som(os.path.join(notas, "g1.wav"))
  time.sleep(0.51)
  tocar_som(os.path.join(notas, "a1.wav"))
  time.sleep(0.54)
  tocar_som(os.path.join(notas, "g1.wav"))
  time.sleep(0.54)
  tocar_som(os.path.join(notas, "c2.wav"))
  time.sleep(0.54)
  tocar_som(os.path.join(notas, "b1.wav"))
  time.sleep(0.58) 

  tocar_som(os.path.join(notas, "g1.wav"))
  time.sleep(0.53)
  tocar_som(os.path.join(notas, "g1.wav"))
  time.sleep(0.51)
  tocar_som(os.path.join(notas, "a1.wav"))
  time.sleep(0.54)
  tocar_som(os.path.join(notas, "g1.wav"))
  time.sleep(0.54)
  tocar_som(os.path.join(notas, "d2.wav"))
  time.sleep(0.54)
  tocar_som(os.path.join(notas, "c2.wav"))
  time.sleep(0.58) 

  tocar_som(os.path.join(notas, "e2.wav"))
  time.sleep(0.54)
  tocar_som(os.path.join(notas, "e2.wav"))
  time.sleep(0.54)
  tocar_som(os.path.join(notas, "g2.wav"))
  time.sleep(0.51)
  tocar_som(os.path.join(notas, "e2.wav"))
  time.sleep(0.54)
  tocar_som(os.path.join(notas, "c2.wav"))
  time.sleep(0.54)
  tocar_som(os.path.join(notas, "a1.wav"))
  time.sleep(0.54)
  tocar_som(os.path.join(notas, "b1.wav"))
  time.sleep(0.54)

  tocar_som(os.path.join(notas, "f2.wav"))
  time.sleep(0.53)
  tocar_som(os.path.join(notas, "f2.wav"))
  time.sleep(0.51)
  tocar_som(os.path.join(notas, "e2.wav"))
  time.sleep(0.54)
  tocar_som(os.path.join(notas, "c2.wav"))
  time.sleep(0.54)
  tocar_som(os.path.join(notas, "d2.wav"))
  time.sleep(0.54)
  tocar_som(os.path.join(notas, "c2.wav"))
  time.sleep(0.58) 
   

  tocar_som(os.path.join(notas, "g1.wav"))
  time.sleep(0.54)
  tocar_som(os.path.join(notas, "c2.wav"))
  time.sleep(0.54)
  tocar_som(os.path.join(notas, "c2.wav"))
  time.sleep(0.58) 
  tocar_som(os.path.join(notas, "c2.wav"))
  time.sleep(0.58) 

  tocar_som(os.path.join(notas, "g1.wav"))
  time.sleep(0.54)
  tocar_som(os.path.join(notas, "d2.wav"))
  time.sleep(0.54)
  tocar_som(os.path.join(notas, "b1.wav"))
  time.sleep(0.58) 
  tocar_som(os.path.join(notas, "c2.wav"))
  time.sleep(0.58)

  tocar_som(os.path.join(notas, "g1.wav"))
  time.sleep(0.54)
  tocar_som(os.path.join(notas, "c2.wav"))
  time.sleep(0.54)
  tocar_som(os.path.join(notas, "e2.wav"))
  time.sleep(0.58) 
  tocar_som(os.path.join(notas, "g2.wav"))
  time.sleep(0.58)

  tocar_som(os.path.join(notas, "e2.wav"))
  time.sleep(0.54)
  tocar_som(os.path.join(notas, "c2.wav"))
  time.sleep(0.54)
  tocar_som(os.path.join(notas, "g1.wav"))
  time.sleep(0.51)
  tocar_som(os.path.join(notas, "d2.wav"))
  time.sleep(0.54)
  tocar_som(os.path.join(notas, "b1.wav"))
  time.sleep(0.54)
  tocar_som(os.path.join(notas, "c2.wav"))
  time.sleep(0.54)

  time.sleep(2)

@------------------------------------------------------------------------------------------@
def twinkle_twinkle_little_star():
  tocar_som(os.path.join(notas, "c3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "c3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "a3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "a3.wav"))
  time.sleep(0.5) 
  tocar_som(os.path.join(notas, "b3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "b3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "a3.wav"))
  time.sleep(0.7) 

  tocar_som(os.path.join(notas, "g3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "g3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "e3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "e3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "d3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "d3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "c3.wav"))
  time.sleep(0.7)

  tocar_som(os.path.join(notas, "a3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "a3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "g3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "g3.wav"))
  time.sleep(0.5) 
  tocar_som(os.path.join(notas, "e3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "e3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "d3.wav"))
  time.sleep(0.7)

  tocar_som(os.path.join(notas, "a3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "a3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "g3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "g3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "e3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "e3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "d3.wav"))
  time.sleep(0.7)

  tocar_som(os.path.join(notas, "c3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "c3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "a3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "a3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "b3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "b3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "a3.wav"))
  time.sleep(0.7)

  tocar_som(os.path.join(notas, "g3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "g3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "e3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "e3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "d3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "d3.wav"))
  time.sleep(0.5)
  tocar_som(os.path.join(notas, "c3.wav"))
  time.sleep(0.7)

  time.sleep(2)
